name: Build SGLang Base Docker Image

on:
  push:
    tags:
      - 'v*'  # 匹配所有以v开头的标签，如v1.0.0, v2.1.0等
  pull_request:
    types:
      - closed
      - opened
      - synchronize
      - edited
    branches:
      - main
    paths:
      - 'images/**'

jobs:
  build-dev:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          docker-images: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: false

      - name: Login to Tencent Cloud Registry
        uses: docker/login-action@v2
        with:
          registry: furion-sh.tencentcloudcr.com
          username: tcr$global-image-service
          password: ZmBfL5iOlecAwtk8K7b2QkdbNu1akXDL

      - name: Build and Push SGLang Base Image
        run: |
          docker build . -f images/Dockerfile.base -t furion-sh.tencentcloudcr.com/furion/sglang-base:latest --no-cache
          docker push furion-sh.tencentcloudcr.com/furion/sglang-base:latest
